fragment presentation on Presentation {
  id
  type
  raw {
    path(format: $filePathFormat)
    modTime
    size
  }
  thumb {
    path
  }
  regular {
    path
  }
  isRegularOutdated
  isRegularTranscodeFailed
}
