fragment presentation on Presentation {
  id
  type
  raw {
    path(format: $filePathFormat)
    modTime
    size
  }
  thumb {
    url
  }
  isThumbTranscodeFailed
  regular {
    url
  }
  isRegularOutdated
  isRegularTranscodeFailed
  metadata {
    k
    v
  }
}
