version: '2.4'
services:
  web:
    build: '.'
    volumes:
      - '/mnt/y:/y:ro'
      - '/mnt/z:/z:ro'
  worker:
    volumes:
      - '/mnt/y:/y:ro'
      - '/mnt/z:/z:ro'
    cpu_shares: 128
    cpus: 4
    mem_limit: 1G
  nginx:
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - 80:80
