type ClientConfig {
  sentryDSN: String
  sentryTracesSampleRate: Float
  issueTrackerURL: String
  enableCGTeamwork: Boolean!
  folderInclude(format: String): [String!] @goField(forceResolver: true)
}

extend type Query {
  clientConfig(name: String!): ClientConfig
}
