extend type Query {
  collections(
    originPrefix: String
    presentationCountGt: Int
    tagOr: [String!]
    tagAnd: [String!]
    first: Int
    last: Int
    before: String
    after: String
  ): CollectionConnection!
}
