#import "@/graphql/fragments/collection.gql"

subscription collectionUpdated(
  $id: [ID!]
  $originPrefix: String
  $presentationCountGt: Int
  $filePathFormat: String
) {
  collectionUpdated(
    id: $id
    originPrefix: $originPrefix
    presentationCountGt: $presentationCountGt
  ) {
    ...collection
  }
}
