type CGTeamworkNote
  @goModel(model: "github.com/WuLiFang/csheet/v6/pkg/cgteamwork.Note") {
  id: ID! @goField(forceResolver: true)
  type: String!
  message: CGTeamworkMessage!
  created: Time!
  createdByName: String!
}

type CollectionCGTeamworkNote {
  pipeline: String!
  notes: [CGTeamworkNote!]!
}

extend type Collection {
  cgteamworkNotes(pipeline: [String!]): [CollectionCGTeamworkNote!]
}
