type Presentation implements Node {
  id: ID!
  type: String!
  raw: File!
  thumb: File
  isThumbOutdated: Boolean
  isThumbTranscodeFailed: Boolean
  regular: File
  isRegularOutdated: Boolean
  isRegularTranscodeFailed: Boolean
}
