type Presentation implements Node {
  id: ID!
  type: String!
  raw: DiskFile!
  thumb: WebFile
  isThumbOutdated: Boolean
  isThumbTranscodeFailed: Boolean
  regular: WebFile
  isRegularOutdated: Boolean
  isRegularTranscodeFailed: Boolean
}
