query cgteamworkProjects($q: String, $status: [String!], $database: [String!]) {
  cgteamworkProjects(q: $q, status: $status, database: $database) {
    database
    name
    codename
    status
  }
}
