#import "@/graphql/fragments/Collection.gql"
#import "@/graphql/fragments/PageInfo.gql"

query collections(
  $after: String
  $before: String
  $first: Int
  $last: Int
  $originPrefix: String
  $filePathFormat: String
  $presentationCountGt: Int
  $tagOr: [String!]
  $tagAnd: [String!]
) {
  collections(
    after: $after
    before: $before
    first: $first
    last: $last
    originPrefix: $originPrefix
    presentationCountGt: $presentationCountGt
    tagOr: $tagOr
    tagAnd: $tagAnd
  ) {
    nodes {
      ...Collection
    }
    pageInfo {
      ...PageInfo
    }
  }
}
