#import "@/graphql/fragments/cgteamworkNote.gql"

query collectionCGTeamworkNotes($id: ID!, $pipeline: [String!]) {
  node(id: $id) {
    id
    ... on Collection {
      cgteamworkNotes(pipeline: $pipeline) {
        pipeline
        notes {
          ...cgteamworkNote
        }
      }
    }
  }
}
