query collectionCGTeamworkNotes($id: ID!, $pipeline: [String!]) {
  node(id: $id) {
    id
    ... on Collection {
      cgteamworkNotes(pipeline: $pipeline) {
        pipeline
        notes {
          type
          message {
            html
            images {
              max {
                url
              }
              min {
                url
              }
            }
          }
          created
          createdByName
        }
      }
    }
  }
}
