#import "@/graphql/fragments/PageInfo.gql"

query collectionTags(
  $after: String
  $before: String
  $first: Int
  $last: Int
  $regex: String
) {
  collectionTags(
    regex: $regex
    after: $after
    before: $before
    first: $first
    last: $last
  ) {
    nodes
    pageInfo {
      ...PageInfo
    }
  }
}
