/* tslint:disable */
/* eslint-disable */
// @generated
// This file was automatically generated and should not be edited.

//==============================================================
// START Enums and Input Objects
//==============================================================

/**
 * Autogenerated input type of CollectFromCGTeamwork
 */
export interface CollectFromCGTeamworkInput {
  database: string;
  prefix: string;
  pipeline: string;
  clientMutationId?: string | null;
}

/**
 * Autogenerated input type of CollectFromFolder
 */
export interface CollectFromFolderInput {
  root: string;
  clientMutationId?: string | null;
}

/**
 * Autogenerated input type of CreateCGTeamworkNote
 */
export interface CreateCGTeamworkNoteInput {
  data: CreateCGTeamworkNoteInputData[];
  username: string;
  password: string;
  clientMutationId?: string | null;
}

export interface CreateCGTeamworkNoteInputData {
  id: string;
  pipeline: string;
  html: string;
  images?: import('./scalars').Upload[] | null;
}

/**
 * Autogenerated input type of DeleteCGTeamworkNote
 */
export interface DeleteCGTeamworkNoteInput {
  id: string[];
  username: string;
  password: string;
  clientMutationId?: string | null;
}

/**
 * Autogenerated input type of UpdateCGTeamworkFlow
 */
export interface UpdateCGTeamworkFlowInput {
  data: UpdateCGTeamworkFlowInputData[];
  username: string;
  password: string;
  clientMutationId?: string | null;
}

export interface UpdateCGTeamworkFlowInputData {
  id: string;
  stage: string;
  status: string;
  pipeline?: string | null;
  note?: string | null;
  images?: import('./scalars').Upload[] | null;
}

/**
 * Autogenerated input type of UpdateCollectionMetadata
 */
export interface UpdateCollectionMetadataInput {
  data: UpdateCollectionMetadataInputData[];
  clientMutationId?: string | null;
}

export interface UpdateCollectionMetadataInputData {
  id: string;
  key: string;
  value: string;
}

/**
 * Autogenerated input type of UpdatePresentationMetadata
 */
export interface UpdatePresentationMetadataInput {
  data: UpdatePresentationMetadataInputData[];
  clientMutationId?: string | null;
}

export interface UpdatePresentationMetadataInputData {
  id: string;
  key: string;
  value: string;
}

//==============================================================
// END Enums and Input Objects
//==============================================================
