/* tslint:disable */
/* eslint-disable */
// @generated
// This file was automatically generated and should not be edited.

//==============================================================
// START Enums and Input Objects
//==============================================================

/**
 * Autogenerated input type of UpdateCollectionMetadata
 */
export interface UpdateCollectionMetadataInput {
  data: UpdateCollectionMetadataInputData[];
  clientMutationId?: string | null;
}

export interface UpdateCollectionMetadataInputData {
  id: string;
  key: string;
  value: string;
}

/**
 * Autogenerated input type of UpdatePresentationMetadata
 */
export interface UpdatePresentationMetadataInput {
  data: UpdatePresentationMetadataInputData[];
  clientMutationId?: string | null;
}

export interface UpdatePresentationMetadataInputData {
  id: string;
  key: string;
  value: string;
}

//==============================================================
// END Enums and Input Objects
//==============================================================
